### ISSUE TITLE
Team A2 - Sprint 1 - Geometriák létrehozása

### ISSUE THREAD

**Issue by BozsikZsolt** [SzFMV2020-Osz/AutomatedCar-A#26]
- [ ] Az objektummodellek geometriájának létrehozása

- Minden entitásnak lesz egy geometriája, ami alapján ütközhet más entitásokkal

- Geometriák parszolása JSON fájlból.

**Comment by pintergreg** [comment]
Ez az issue abból a szempontból biztos pontatlan, hogy a geometriák már meghatározásra kerültek korábbi félévben és JSON formában elérhetőek.

Azt hiszem, hogy van egy-két útelem típus amire nem csinálták meg, mert az a pálya a múltkor nem volt használva (ebben nem vagyok biztos), de alapból megvannak. Tehát csak parse-oleni kell és beletenni a modell osztályokba.

Visszavonom azt, hogy hibás az issue, mivel úgy látom, hogy a user story-ba nem tettem bele, [csak a jegyzetben szerepel.](https://szfmv2020-osz.github.io/handout/sprint_1.html#vil%C3%A1gmodell-kialak%C3%ADt%C3%A1sa)
@SzFMV2020-Osz/team-a2 @SzFMV2020-Osz/team-b2 Elnézést, ezt nem kommunikáltam megfelelően.

edit: [Erről a fájlról van szó](https://github.com/SzFMV2020-Osz/AutomatedCar-A/blob/master/src/AutomatedCar/Assets/worldobject_polygons.json).
