### ISSUE TITLE
Egyeztetés a A2 csapattal a kirajzolandó elemekkel kapcsolatban

### ISSUE THREAD

**Issue by Gergo38** [SzFMV2020-Osz/AutomatedCar-A#32]
- [x] Kirajzolandó elemek megszerzésének módjának megtárgyalása

**Comment by bozsobence** [comment]
Eredmény: egy listában fogják tárolni a megjelenítendő objektumokat, ezeket fogjuk tudni elérni egy publikus tulajdonságon keresztül.
